### ISSUE TITLE
Rename Identity function

### ISSUE THREAD

**Issue by jskulavik** [microsoft/fit-on-fhir#13]
Jarrod and Nyemade would like to change the name of this function to better reflect the purpose of this function as we currently understand it - to _manage_ identity AND access management.

Our current understanding of what this function does is:
- Allows user consent for this connector to obtain PHI from Google's Fitness API
- Generates a user record in FHIR
- Obtains an OAuth2 refresh token
- Writes user record to Azure storage table

Given that, we would like to change the name from `Identity` to `IAM`.

**Comment by namalu** [comment]
All functions have been renamed.
